orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/KafkaIdealBalanceAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/ReassignmentAction.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicSensor.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Allow configurable timeout for metadata fetch in rebalancing action. Default is 30s.

Allow configurable metadata fetch timeout for rebalances

---

orion-server/src/main/java/com/pinterest/orion/core/actions/alert/PagerDutyAlert.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java

Add a transient state in BrokerHealingOperator to denoise unhealthy broker alerts. Fixed Pagerduty Alert format.

Add transient state for unhealthy broker alerts to reduce noise

---

deployments/orion-server-deployment/conf/kafka-server.yaml
docs/Kafka/README.md
orion-server/scripts/config.yaml
orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/AssignmentDeleteKafkaTopicAction.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaClusterInfoSensor.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Topic config files that include a top level entry of will result in the topic being deleted.
There is currently no other check/balance on the topic. If the config file is changed to include that flag, that topic will be removed. I'd love to hear any feedback about other potential handles to make this safer. On the other side I'm planning to do a similar alert setup to the topic creation flow
Testing: Tested locally with a local kafka cluster that Ping helped me set up.

Topic Deletion

---

docs/Kafka/README.md

I forgot to add a mention in the doc about the guard to prevent careless deletions using Orion. I added a blurb about it to make sure it would be obvious.
Testing: Didn't bother as this change is completely non-functional, just a readme modification

Small change to the readme doc for increased clarity

---

orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Currently this try/catch is only catching ExecutionException, so timeouts do not have a chance to recover like ExecutionExceptions do.

Catching all the possible exceptions for getting topic metadata

---

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java

BrokersetTopicOperator had an issue where if a topic which was marked for deletion had a brokerset that didn't exist then there would be a null pointer exception way down the line. Now this situation is logged and will cause the operator to move to the next topic instead of dying unceremoniously

Fixing failure to create topics

---

deployments/orion-server-deployment/pom.xml
orion-agent/pom.xml
orion-server/pom.xml

Main priority for this update is to gain access to the new instance types that haven't been added until recently.

Updating software.amazon.awssdk to 2.17.273

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaBrokerConfigSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaBrokerSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaConsumerGroupDescriptionSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaConsumerGroupOffsetSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaLogDirectorySensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicOffsetSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java
orion-server/src/test/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensorTest.java

Default timeout causes some sensors unnecessarily fail due to large data set. 
The sensor will load timeout value from cluster attribute and use the value as timeout parameter for Admin Client API call through request options. If cluster does not have required attributes, the AdminClient call will use default timeout values (empty option).
There are three types of attribute keys for three types of Admin Client API calls. 
- KafkaAdminClientClusterRequestTimeoutMs is used for AdminClient cluster/broker config APIs.
- Ex: describeConfigs and describeCluster
- KafkaAdminClientTopicRequestTimeoutMs is used for AdminClient topic/partition related APIs.
- Ex: describeLogDirs and listOffsets
- KafkaAdminClientConsumerGroupRequestTimeoutMs is used for AdminClient consumer group related APIs.
- …

Add configurable timeouts for sensors using Kafka Admin API

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensor.java
orion-server/src/test/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensorTest.java

Cluster configurations in yaml file are not added as cluster attributes automatically. They are stored in cluster configuration attribute map after initialization. This commit updates the getKafkaAdminClient*RequestTimeoutMilliseconds function to get value from cluster conf attribute map instead of cluster attribute. 
Change the config keys to make them start with lower letter. 
Update unit test

Get kafka admin client timeout config from config atrribute

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensor.java
orion-server/src/test/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaSensorTest.java

Add logic to handle null value from cluster.getAttribute
cluster.getAttribute(Cluster.ATTR_CONF_KEY) might be null. If it's null, it can trigger NPE. Add logic to prevent this from causing failures.

Add logic to handle null value from cluster.getAttribute

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaBrokerConfigSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaBrokerSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaConsumerGroupDescriptionSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaConsumerGroupOffsetSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaLogDirectorySensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicOffsetSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java
orion-server/src/test/java/com/pinterest/orion/core/kafka/KafkaClusterTest.java

The previous change gets NPE from getKafkaAdminClientClusterRequestTimeoutMilliseconds. All KafkaCluster.getKafkaAdminClientClusterRequestTimeoutMilliseconds happens after containsKafkaAdminClientClusterRequestTimeoutMilliseconds. I don't know why the error can happen. 
I have one assumption that both containsKafkaAdminClientClusterRequestTimeoutMilliseconds and getKafkaAdminClientClusterRequestTimeoutMilliseconds are calling getClusterConfMap. But getClusterConfMap is not guarantee to return the same thing. Cluster config might be changed or updated between two call.
Therefore, I combine get and contain function. If the value does not exist, use -1 to indicate it. This can make two functions atomic. The getClusterConfMap will only be called once for both check and get value. 
Add logs …

Add logging into KafkaCluster methods; Return default value with WARN message if the get timeout function is called but the value does not exist

---

orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java
orion-server/src/test/java/com/pinterest/orion/core/kafka/KafkaClusterTest.java

Yaml file can be loaded config as int. Add type check and int handling logic.

Add object type check so KafkaCluster can support both String and int

---

orion-server/src/main/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelper.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
orion-server/src/test/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelperTest.java

ActionNotificationHelper is used by Action class to send notifications in Orion. It supports Slack for its first version but can be extended to other type of messages (ex. page_duty). 
For each action, the helper is created in initialization with action itself and config. Based on the config, the helper will decide whether to send notifications and what's its destinations. If the config does not have required parameters, nothing will happen. 
When the message needs to be sent, simply call notificationHelper.sendNotifications();
Sample config 
```
- clusterId: test_kafka_cluster
type: kafka
configuration:
slackWebhookUrlList: 
- {url_1}
- {url_2}
```
Sample usage
* See orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java

Slack notification feature

---

orion-server/src/main/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelper.java
orion-server/src/test/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelperTest.java

While testing ActionNotificationHelper, i found the constructor does not have a logic to handle null value in the input list. The helper will throw error while calling sendSlackNotifications instead of throwing it at beginning. 
* Add logic to do basic not-null check in constructor. 
* Add logging prefix to make log easy searchable
* Add one more unit test

Add logic to handle null value in config list; Add related unit test

---

orion-server/src/main/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelper.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
orion-server/src/test/java/com/pinterest/orion/core/actions/alert/ActionNotificationHelperTest.java

Update ActionNotificationHelper logic 
* Allow to set owner
* Remove get title/message from initialization. 
* Add get engine non-null check. The engine is not ready while initializing the action.
Add pre-defined notification message in ReplaceEC2InstanceAction
* getName in action class is not that good. Use predefined messages. 
* Use isSendingNotifications to check whether to send messages. Then add personalized messages.

Update ActionNotificationHelper logic; Add pre-defined notification message in ReplaceEC2InstanceAction

---

orion-agent/src/main/java/com/pinterest/orion/agent/BaseAgent.java
orion-agent/src/main/java/com/pinterest/orion/agent/OrionAgentConfig.java

Load metrics call timeout value from config to avoid timeout error while calling metricFuture.get
The agent needs config for initialization so the getConfig wont return a null value.

Load metrics call timeout value from config

---

orion-agent/src/main/java/com/pinterest/orion/agent/OrionAgentConfig.java
orion-agent/src/main/java/com/pinterest/orion/agent/kafka/KafkaAgent.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Make the timeout value used in describeCluster configurable. This should fix the common timeout issue of getServiceStatus method in orion agent.
I make the AdminClient.describeCluster and future.get function sharing the same timeout value to reduce the ambiguity. 
The config key is describeClusterTimeoutMs. The value is milliseconds (because DescribeClusterOptions takes Ms). Default value was set to 10 sec (10000 ms).

Add configurable timeout value for agent describe cluster call 

---

orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Topic sensor can cache topic info but reassignment action cannot do that. I add a cache logic in KafkaCluster class. If the cache has not been created yet (no attribute), just initialize it. This should benefit the while loop check in reassignment action. The cache can still be updated by topic sensor

Allow KafkaCluster to initialize topic info cache if the cache does not exist

---

deployments/orion-agent-deployment/pom.xml
deployments/orion-server-deployment/pom.xml
deployments/pom.xml
orion-agent/pom.xml
orion-agent/src/main/java/com/pinterest/orion/agent/utils/MetricUtils.java
orion-commons/pom.xml
orion-server/pom.xml
pom.xml

java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long 
At MetricUtils.java:121
Use Double.longValue() to convert the double value into long instead of directly call "(long)"

Fix java.lang.ClassCastException bug

---

deployments/orion-agent-deployment/pom.xml
deployments/orion-server-deployment/pom.xml
deployments/pom.xml
orion-agent/pom.xml
orion-agent/src/main/java/com/pinterest/orion/agent/utils/MetricUtils.java
orion-commons/pom.xml
orion-server/pom.xml
pom.xml

Add try-catch and conversion logic to avoid ClassCastException in convertGauges
getGaugesEntryValueNumber should be able to handle all types of Object. If the object is null or cannot be parsed as a string, it will throw exception so the outer for loop will just continue to the next one. 
Upgrade to 0.0.39 for orion agent deployment

Add try-catch and conversion logic to avoid ClassCastException in convertGauges

---

deployments/orion-agent-deployment/pom.xml
deployments/orion-server-deployment/pom.xml
deployments/pom.xml
orion-agent/pom.xml
orion-agent/src/main/java/com/pinterest/orion/agent/utils/MetricUtils.java
orion-commons/pom.xml
orion-server/pom.xml
pom.xml

Add try-catch and conversion logic to avoid ClassCastException in convertCounters
The registry with empty gauges can also have empty counters. Need to handle them both.

Add try-catch and conversion logic to avoid ClassCastException in convertCounters

---

deployments/orion-agent-deployment/pom.xml
deployments/orion-server-deployment/pom.xml
deployments/pom.xml
orion-agent/pom.xml
orion-agent/src/main/java/com/pinterest/orion/agent/HeartbeatService.java
orion-agent/src/main/java/com/pinterest/orion/agent/utils/MetricUtils.java
orion-commons/pom.xml
orion-server/pom.xml
pom.xml

Change MetricUtils logics: If getGaugesEntryValueNumber fails, the heartbeat won't contain partial metrics.
I check the agent log. In heartbeat message, if metrics contain partial data, the heartbeat requests are failing. So I just let all exception be handled in registerWithServer instead of skipping individual metrics section with parsing failures.

Change MetricUtils logics: If getGaugesEntryValueNumber fails, dont send partial metrics

---

deployments/orion-agent-deployment/pom.xml
deployments/orion-server-deployment/pom.xml
deployments/pom.xml
orion-agent/pom.xml
orion-agent/src/main/java/com/pinterest/orion/agent/HeartbeatService.java
orion-commons/pom.xml
orion-server/pom.xml
pom.xml

I compare two heartbeat json logs, one from agent with URP contains
```
..."metrics":{"metrics":[]},"containsMetrics":true,"readOnly":false}
```
One from agent without error contains
```
..."metrics":null,"containsMetrics":false,"readOnly":false}
```
In this case, I simply keep heartbeat without metrics if getValue fails.

Keep metrics null instead of setting an empty value

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java
orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java

Publish kafka topic metrics including topic size in byte, number of partitions and retention period in ms
* In KafkaTopicSensor, add a new function called populateTopicMetrics to publishing those metrics.
* In OrionServer, add a new helper called metricsGaugeNum for publishing numeric values. 
* Slightly refactor the logic of making MetricName and MetricsTag.

Publish kafka topic metrics including topic size in byte, number of partitions and retention period in ms

---

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/RebootEC2InstanceAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/TerminateEC2InstanceAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/MinIsrRfConflictResolutionAction.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java
orion-server/src/main/java/com/pinterest/orion/core/memq/MemqBroker.java

* Add a null check in MemQ getTopicPartitionsForNode
* If the broker was removed, getTopicPartitionsForNode method of that node can still be called because the currentNodeInfo is in ClusterManager nodeMap. However, the nodeId is not rawBrokerMap in next ClusterSensor refresh. This can cause exception and make UI crush.
* getAssignedTopics is returning a Set<TopicConfig>. I let the empty return to be a Set<> to make them consistent. 
* Revert metricsCounterInc change

Add a null check in MemQ getTopicPartitionsForNode; Revert metricsCounterInc change

---

orion-server/src/main/java/com/pinterest/orion/core/Node.java
orion-server/src/main/java/com/pinterest/orion/core/memq/MemqBroker.java
orion-server/src/main/resources/webapp/src/basic-components/Nodes.js

Check node status tag. If the tag is DECOMMISSIONED, the node will no longer be shown in UX.
DECOMMISSIONED tag is not used at other places. Kafka node wont be impacted and can also benefit from this feature.

Hide memq broker if broker is no longer in ZK

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqClusterSensor.java
orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqTopic.js

Show broker name in memq topic page. Now it's showing the broker ip address.
ClusterSensor is recording a string array and sends it to MemqTopic.js for renderning. I just make it record host name strings instead of ip strings. I dont plan to change it to map array to render more things now.

Show broker name in memq topic page

---

orion-server/src/main/java/com/pinterest/orion/core/actions/generic/ServiceStabilityCheckAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/BrokerRecoveryAction.java
orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/ClusterRecoveryAction.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java
orion-server/src/test/java/com/pinterest/orion/core/actions/kafka/TestClusterRecoveryAction.java

Implement ClusterRecoveryAction: Orion can automatically recover more than one brokers now. 
Broker issue can be detected by BrokerHealingOperator. Before this change, if one broker has outage, BrokerHealingOperator will trigger one BrokerRecoveryAction to recovery it. If more than one brokers have issues, BrokerHealingOperator just throws errors and does nothing.
This PR adds a layer ClusterRecoveryAction between BrokerHealingOperator and BrokerRecoveryAction. When BrokerHealingOperator detects one or more brokers with issues, it creates and dispatches a ClusterRecoveryAction to take care of it. ClusterRecoveryAction can decide whether to create multiple BrokerRecoveryActions to fix broker issues based on its own logic. 
To avoid one broker being fixed multiple time, the PR introduces a …

Implement ClusterRecoveryAction

---

orion-server/src/main/java/com/pinterest/orion/core/ClusterManager.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/AmiTagManager.java
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java
orion-server/src/main/java/com/pinterest/orion/server/api/ClusterManagerApi.java
orion-server/src/main/resources/webapp/src/actions/cluster.js
orion-server/src/main/resources/webapp/src/basic-components/Ami.js
orion-server/src/main/resources/webapp/src/reducers/app.js
orion-server/src/main/resources/webapp/src/sagas/index.js

Ami tag management aims to promote Amis through successive environments, like dev -> stage -> prod. This change enables a list of environments to be configurable.

Configurable environment types for Ami tag management

---

orion-commons/src/main/java/com/pinterest/orion/common/NodeInfo.java
orion-server/pom.xml
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/clickhouse/ClickHouseClusterSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/clickhouse/ClickHouseSensor.java
orion-server/src/main/java/com/pinterest/orion/core/clickhouse/ClickHouseCluster.java
orion-server/src/main/java/com/pinterest/orion/core/clickhouse/ClickHouseNodeInfo.java
orion-server/src/main/java/com/pinterest/orion/server/ClusterTypeMap.java
orion-server/src/test/resources/configs/clickhouse-server.yaml

- Expands ClickHouse cluster and nodes classes in Orion to store more info, including shard/replica associated with each node
- Adds a sensor that can be run periodically to update the ClickHouse cluster topology in Orion
- Deploy a ClickHouse cluster for testing (I've used [this here](https://github.com/tetafro/clickhouse-cluster), deployed locally via Docker)
- Create a test serverset file with all the nodes' info listed (`<ip>:<port>`); add the serverset path to the test `clickhouse-server.yaml` file
- Run Orion server with the test `clickhouse-server.yaml` config file passed in; verify that the proper ClickHouse nodes info are being sensed in the logs
- Add / remove nodes in the local ClickHouse cluster; also register new logical clusters (by running …

Add Orion sensor for ClickHouse clusters/nodes

---

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/AmiTagManager.java
orion-server/src/main/java/com/pinterest/orion/server/api/Ami.java
orion-server/src/main/java/com/pinterest/orion/server/api/ClusterManagerApi.java
orion-server/src/main/resources/webapp/src/basic-components/Ami.js

Fixes architecture filter in the dynamic AMI selection.

Dynamic AMI selection: fix architecture filter

---

orion-server/src/main/java/com/pinterest/orion/core/actions/generic/NodeAction.java

Update default recovery check timeout value. The original value (1 min) is too small. Change to 30 mins.
Also make these two values as constant values instead of keeping them in methods.

Update node recovery check timeout values

---

orion-server/pom.xml
orion-server/src/main/java/com/pinterest/orion/core/actions/aws/S3Utils.java
orion-server/src/main/java/com/pinterest/orion/core/actions/clickhouse/PublishAllNodeConfigAction.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/clickhouse/ClickHouseOperator.java
orion-server/src/main/java/com/pinterest/orion/core/automation/operator/clickhouse/PublishConfigOperator.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/clickhouse/ClickHouseClusterSensor.java
orion-server/src/main/java/com/pinterest/orion/core/clickhouse/ClickHouseCluster.java
orion-server/src/main/java/com/pinterest/orion/core/clickhouse/ClickHouseNodeInfo.java
orion-server/src/test/resources/configs/clickhouse-server.yaml

Whenever new servers are added to or removed from a ClickHouse cluster, each node has to go with a new config specifying the updated list of replica servers for each shard.
This PR helps to simplify that process by automatically generating the config for each ClickHouse node from a given template config by:
- dynamically listing the replicas for each shard from the model of the cluster sensed/stored in memory (see this [PR](https://github.com/pinterest/orion/pull/281)); this part is the same across the configs for all nodes
- sub in the specific shard and replica number for the node
Once generated, Orion server will then publish the configs for each node to the given S3 bucket under the path `<node_hostname>/config.xml`. It is expected that the Orion agent will then pull the config for a …

Generate and publish ClickHouse node configs

---

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java

Implement additional configuration, valid for the all clusters in the Orion server, to set a volume size that overrides the original AMI size.

LP-7512 Add feature to override AMI root volume size

---

orion-commons/src/main/java/com/pinterest/orion/common/NodeInfo.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/BrokersetStateSensor.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/BrokersetState.java
orion-server/src/main/resources/webapp/src/basic-components/Kafka/BrokersetEntry.js
orion-server/src/main/resources/webapp/src/basic-components/Kafka/Brokersets.js
orion-server/src/main/resources/webapp/src/basic-components/Kafka/KafkaNode.js

- Introduced a new header.  
- Added three sub-sections:  
1. **Assignments:** Displays start broker ID to end broker ID.  
2. **Broker Links**  
3. **Status:** Reserved for future use.  
- Added a new label in the header to show the broker set count.  
- Introduced a broker set section that records all broker sets.  
- Added a broker status section, which is reserved for future use.  
The existing `BrokerSet` class is generated from a configuration file every 2 minutes, which means it cannot currently save state information. Additionally, it plays a critical role in the existing topic assignment logic. To avoid disrupting any existing logic during refactoring, a new `BrokerSetState` class has been added.  
This change has been tested via branch deployment.

Orion Broker Set UI Implementation 

---

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/AmiTagManager.java
orion-server/src/main/java/com/pinterest/orion/server/api/ClusterManagerApi.java
orion-server/src/main/resources/webapp/src/basic-components/Ami.js

AMI tag 'environment' allow values prod and test. When replacing nodes in Kafka clusters it's important to be able to select AMIs based on their tag 'environment', along with other criteria.
Cluster configuration:
```
- clusterId: upgradekafka01
type: kafka
configuration:
image:
application: kafka
release: bionic
architecture: x86_64
environment: test
application_environment: dev
```
Target AMI correctly tagged:
Node replacement successful with correct AMI:
Cluster configuration (no environment, defaults to prod):
```
- clusterId: upgradekafka01
type: kafka
configuration:
image:
application: kafka
release: bionic
architecture: x86_64
application_environment: dev
```
Target AMI correctly tagged:
Node replacement successful:
```
brunorodrigues@lancerkafka-canary-0a033c99:~$ tail -f …
```

Add tag:environment to AMI filter criteria

---

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java

Fixes:
- Convert topicSize and retentionMs from interger to long. So the large topic or long rention topic wont cause sensor parsing error. 
- Attach broker id into metrics datapoints to help the engineer find out which brokers are in bad state.

Make retention.ms be long; Attach broker id into metrics datapoints

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqClusterSensor.java

If brokers are removed outside orion, the zk call getting broker data can fail. Add logic to handle this exception. 
After the loop, the sensor also updates the cluster broker map to make sure all nodes are still in ZK.

Fix orion error caused by brokers removed outside orion

---

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqClusterSensor.java
orion-server/src/main/java/com/pinterest/orion/core/utils/memq/zookeeper/MemqZookeeperClient.java

This PR addresses an issue where the MemQ Cluster Sensor could fail after running for an extended period by introducing a mechanism to refresh the `CuratorFramework` client upon encountering ZK call exceptions. Previously, after MemQ orion ran for some time, the `CuratorFramework` might consistently throw exceptions, requiring engineers to restart orion to restore the system to a normal state. With this update, the client is now automatically recreated when exceptions occur. The newly instantiated client is attached to the MemQ cluster class, ensuring continuous availability.  
- **Refreshed Zookeeper Client**:  
- The `CuratorFramework` client is now refreshed automatically on encountering exceptions, enhancing system reliability and reducing manual intervention. This feature can be …

Enhancements to MemQ Cluster Sensor  

---

orion-commons/src/main/java/com/pinterest/orion/common/NodeInfo.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/BrokerMetricsSensor.java
orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/BrokersetStateSensor.java
orion-server/src/main/java/com/pinterest/orion/core/kafka/BrokersetState.java
orion-server/src/main/resources/webapp/src/basic-components/Kafka/BrokersetEntry.js
orion-server/src/main/resources/webapp/src/basic-components/Kafka/Brokersets.js
orion-server/src/main/resources/webapp/src/basic-components/Kafka/KafkaNode.js

This update enables Orion to store and display metrics for brokers and brokersets within the Orion interface.  
- Introduces two new maps:  
- **`rawBrokerStatus`**: Stores raw data from the metrics API call as a map of `String -> Double`. Example: `cpu_usage -> 0.22`.  
- **`brokerStatus`**: Contains the keys and values that are displayed in the Orion UI. Both values are strings. Example: `"CPU Usage"` and `"22%"`.  
- Also includes two new maps:  
- **`rawBrokersetStatus`**: Stores raw data after aggregating values across all brokers as a map of `String -> Double`. Example: `max_cpu_usage -> 0.22`.  
- **`brokersetStatus`**: Contains the keys and values to be shown in the Orion UI. Both values are strings. Example: `"Max CPU Usage Across All Brokers"` and `"22%"`.  
- This class will be …

Display Broker and Brokerset Information in Orion UI  

---

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java

To avoid validating brokerset of deleted topics, move the check block to after where deleted topics are processed.
This change should avoid warning messages like this in the log for deleted topics:
```
com.pinterest.orion.core.automation.operator.kafka.BrokersetTopicOperator: Topic(...) Attempted to use Brokerset(...) which doesn't exist.
```

Move brokerset check block
