pinterest/orion

orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/AssignmentCreateKafkaTopicAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/AssignmentExpandKafkaTopicAction.java
=> Fix merge headers

orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqNode.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/Topics.js, orion-server/src/main/resources/webapp/src/basic-components/Nodes.js, orion-server/src/main/resources/webapp/src/basic-components/Service.js
=> Updates for memq ui

orion-commons/src/main/java/com/pinterest/orion/utils/NetworkUtils.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaClusterInfoSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/Broker.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqClusterSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicDescription.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/TopicConfig.java, orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java, orion-server/src/main/java/com/pinterest/orion/core/memq/MemqBroker.java, orion-server/src/main/java/com/pinterest/orion/core/memq/MemqCluster.java, orion-server/src/main/java/com/pinterest/orion/server/api/CustomApiFactory.java, orion-server/src/main/java/com/pinterest/orion/server/api/kafka/KafkaApiFactory.java, orion-server/src/main/java/com/pinterest/orion/server/api/memq/MemqApiFactory.java, orion-server/src/main/java/com/pinterest/orion/server/api/yarn/YarnApiFactory.java, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqNode.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqService.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqTopic.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/Topics.js, orion-server/src/main/resources/webapp/src/basic-components/Nodes.js
Initial commit for MemQ Orion integration capturing topic and broker info
=> Initial commit for MemQ Orion integration 

.github/workflows/maven.yml, orion-server/scripts/build_ui.sh
=> Fix github build / validation

orion-server/src/main/java/com/pinterest/orion/core/actions/Action.java, orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/AssignmentCreateKafkaTopicAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/memq/MemqTopicCreationAction.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/memq/MemqOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/memq/MemqTopicOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqClusterSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicRepoSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/core/kafka/Brokerset.java, orion-server/src/main/java/com/pinterest/orion/core/memq/MemqCluster.java
=> MemQ Topic Creation Operator

orion-server/src/main/java/com/pinterest/orion/core/actions/memq/MemqTopicCreationAction.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/memq/MemqOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/memq/MemqTopicOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicRepoSensor.java, orion-server/src/main/java/com/pinterest/orion/core/memq/MemqCluster.java
Fix memq topic creation operator bugs
=> Fix memq topic creation operator

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/RebootEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
=> Add hostname to replacement health check failure alert

orion-server/src/main/java/com/pinterest/orion/core/global/sensor/GlobalPluginManager.java, orion-server/src/main/java/com/pinterest/orion/core/global/sensor/GlobalSensor.java, orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java, orion-server/src/main/java/com/pinterest/orion/server/config/OrionConf.java
Add concept of GlobalPlugins and GlobalPluginManager
=> Add concept of GlobalPlugins and GlobalPluginManager

orion-server/src/main/java/com/pinterest/orion/core/global/sensor/GlobalPluginManager.java
=> Add missing method for tests

orion-server/src/main/java/com/pinterest/orion/core/global/sensor/GlobalPluginManager.java, orion-server/src/main/java/com/pinterest/orion/core/global/sensor/GlobalSensor.java, orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java, orion-server/src/main/java/com/pinterest/orion/server/api/ClusterManagerApi.java, orion-server/src/main/resources/webapp/src/actions/clusterSummary.js, orion-server/src/main/resources/webapp/src/basic-components/Automation.js, orion-server/src/main/resources/webapp/src/basic-components/GlobalSensors.js, orion-server/src/main/resources/webapp/src/basic-components/Homepage.js, orion-server/src/main/resources/webapp/src/basic-components/Layout.js, orion-server/src/main/resources/webapp/src/basic-components/SensorCard.js, orion-server/src/main/resources/webapp/src/basic-components/Summary.js, orion-server/src/main/resources/webapp/src/reducers/clustersSummary.js, orion-server/src/main/resources/webapp/src/reducers/globalSensors.js, orion-server/src/main/resources/webapp/src/sagas/index.js
Add globalsensor UI to display status of global sensors
=> Add globalsensor UI

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/TopicConfig.java
Synchronize MemQ topic config default with internal repo
=> Update memq topic config default for enable bucketing 2 processor

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java
Add alerts for degraded service. If Kafka doesn't detect a faulty node but Orion does it would allow getting alerted.
=> Add alerts for degraded service

orion-commons/src/main/java/com/pinterest/orion/configs/StatsConfiguration.java, orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java
- Allow configuration of metrics prefix
- Add a few metrics within replacement action
=> Update orion server/instance replacement metrics

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java
Add more descriptive message for the alerts
=> Fix wording of degraded hosts alerts

orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java
Lists.partitions cannot take 0 as partition size
=> Fixing PR validation for first topic

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaClusterInfoSensor.java
Modify KafkaClusterInfoSensor access for subclass overrides
=> Modify KafkaClusterInfoSensor class access

deployments/orion-server-deployment/conf/kafka-server.yaml, docs/Kafka/README.md, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaClusterInfoSensor.java, orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java
I misunderstood the way configurations were set up so this PR will rectify that mistake.
Testing: Functional testing to make sure there were no behaviour regressions.
=> Change the location of the configuration to let clusters delete topics

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
=> Bump version to 0.0.34

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
Updating the awssdk to support the use of i4i Instance Types.
=> Updating awssdk to 2.17.202

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
Missed a spot in the last pull request. Have to add it now.
=> Adding new aws instance types for ReplaceInstance

orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/KafkaIdealBalanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java, orion-server/src/main/java/com/pinterest/orion/core/kafka/TopicAssignment.java
Overwrote replication factor if partition count & replication factor are changed at the same time so the operator can dispatch the actions in the right order
=> Fix topic expansion issue

orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokersetTopicOperator.java
Added a feature to brokerset operator that prevents an expansion action to be dispatched if the topic's cleanup policy contains "compact"
=> reject partition size increase for compacted topics

orion-agent/src/main/java/com/pinterest/orion/agent/kafka/KafkaAgent.java, orion-server/src/main/java/com/pinterest/orion/core/kafka/KafkaCluster.java
This PR reverts the last two commits on Pinterest orion
We didn't have time this week to figure out the problems that these new commits caused, and are going to postpone that until next week. 
This PR will get the repo back to a consistent state, and after merging the repo will be exactly the same as it was on commit c64bb15
=> Reverting last two commits

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
=> Upgrade version to 0.0.36

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-agent/src/main/java/com/pinterest/orion/agent/HeartbeatService.java, orion-agent/src/main/java/com/pinterest/orion/agent/utils/MetricUtils.java, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
Removing convertGauges and convertCounters number parsing logic.
No metrics in heartbeat if there's parsing error.
=> Removing convertGauges and convertCounters number parsing logic; No metrics in heartbeat if there's parsing error.

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java
Re-adding the ability to replace brokers with i3 instances.
=> Re-adding replace with i3 instances

orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/KafkaDNSUpsertAction.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/DNSRepairOperator.java
Adding an operator to update DNS should any nodes get disconnected due to the removal of a DNS entry
=> Adding DNS repair operator

orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/KafkaDNSUpsertAction.java
Fixing a problem getting the attributes for nodename and ipAddress
=> DNS Action update

orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/KafkaDNSUpsertAction.java
Made a mistake Moving changes from testing environment to this environment. Also went all the way through the integration test rather than stopping once the last problem was proved to be resolved. This test has gone all the way from the removal of the dns entry to the automatic addition of that entry.
=> Fixing problem in error check

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
Updating version for ease of use upstream
=> Updating version

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
=> updating orion version

deployments/orion-agent-deployment/pom.xml, deployments/orion-server-deployment/pom.xml, deployments/pom.xml, orion-agent/pom.xml, orion-commons/pom.xml, orion-server/pom.xml, pom.xml
Also upgrade Kafka client library to 2.3.1.
=> Bump version to 0.0.46

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicSensor.java, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqNode.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqService.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqTopic.js, orion-server/src/main/resources/webapp/src/basic-components/MemQ/Topics.js, orion-server/src/main/resources/webapp/src/basic-components/Nodes.js
* Remove notification topic check in TopicSensor
* Update Service section - Display numeric values in topic configs, remove kafka related info 
* Update Node section - Display topic names in each brokers, remove read partition info 
* isRowSelectable keeps true
=> Implement memq orion ui

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/RebootEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/aws/ReplaceEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/aws/TerminateEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/kafka/MinIsrRfConflictResolutionAction.java, orion-server/src/main/java/com/pinterest/orion/core/automation/operator/kafka/BrokerHealingOperator.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java
Add a metric counter call for high level alert. 
The metrics can be used for different types of alerting system.
=> Add a metric counter call for high level alert

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicDescription.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/MemqTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/memq/TopicConfig.java, orion-server/src/main/resources/webapp/src/basic-components/MemQ/MemqTopic.js
* Add a link map variable into TopicDescription class
* Render a hyperlink list in memq topic page
* Refactor MemqTopicSensor to allow override on sense method
* Update topicConfig print
=> Show useful links in memq topic page

orion-server/src/main/java/com/pinterest/orion/core/actions/aws/RebootEC2InstanceAction.java, orion-server/src/main/java/com/pinterest/orion/core/actions/generic/GenericClusterWideAction.java
* Refactor RebootEC2InstanceAction
* Add set/get for private values
* Change static value / method from private to protected
* Add a ParallelRebootNodeAction as the parent of memq reboot action
=> Refactor RebootEC2InstanceAction.java and GenericClusterWideAction.java to allow inheritance

orion-server/src/main/java/com/pinterest/orion/core/actions/generic/GenericClusterWideAction.java
Add an interface for parallel replacement
=> Add ParallelReplaceNodeAction

orion-server/src/main/java/com/pinterest/orion/core/automation/sensor/kafka/KafkaTopicSensor.java, orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java
Implement metricsHistogram method.
=> Add metricsHistogram method
